### ISSUE TITLE
Native support for UUID class

### ISSUE THREAD

**Issue by mkarg** [javaee/jpa-spec#152]
It would be really great if `UUID` would be a valid type for (at least PK) attributes. Certainly it can be provided by an application using an adapter class, but in the context of massively distributed environments it seems to be a `common` need of all cloud applications.

**Comment by mkarg** [comment]
I developed an `AttributeConverter<UUID>` and could contribute it to the RI.

**Comment by rbygrave** [comment]
Note that I don't see AttributeConverter as sufficient due to the differences in database support - native UUID type in Postgres etc and resulting DDL generation and binding differences.  That is, in my opinion the ORM vendor really ought to deal with those specific details as well (been here, got the T-Shirt).

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/152
