### ISSUE TITLE
suggest new annotation columnDefine

### ISSUE THREAD

**Issue by amwei** [javaee/jpa-spec#153]
new annotation like this:

	@ColumnDefine(name = "remark",comment="",dialect=MySQL5InnoDBDialect.class,define=JDBCType.xxx,defaultValue=Defaults.xxx,size=32,scale=2)
	private String remark;
Attributes:
	1)dialect
		dialect can be auto regiested by @Dialect 

		@Dialect
		public class MySQL5InnoDBDialect{

		}
	2)define 
                      value from java.sql.JDBCType
	3)defaultValue
                      value from Enum Defaults
		
		enum Defaults{
			NULL,EMPTY_STRING,TRUE,FALSE,ZERO,DATE,TIME,DATETIME,TIME_STAMP;
		}

**Comment by andyjefferson** [comment]
The point of having the JPA API is to generalise and standardise things; it is not to just use what one implementation uses itself. Consequently the "dialect" thing would be nonsensical in a standard; it is Hibernate's own way of doing something - there are many different ways of handling datastore-specifics.

Standardising the jdbcType, on the other hand, makes perfect sense, but then it could/should be an attribute on `@Column`, not on its own annotation. So then the provider has the jdbc type, and the length/precision/scale, and from that can define the column more completely without having to fallback to the ghastly "columnDetails" attribute. In fact they could also have "sqlType" as well as "jdbcType", to allow for using specific database types (since jdbcType only defines to a certain level). [It ought to be said that the JDO API standardised jdbcType back in 2004.]

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/153
